# Generated by Django 6.0.5 on 2026-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_usage',
            field=models.IntegerField(default=0),
        ),
    ]
